name = "OptionalArgChecks"
uuid = "dfbeeb84-381a-44da-9ec9-a723abf299c7"
authors = ["Simeon Schaub"]
version = "0.1.0"

[deps]
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
